import Header from '@/components/header/Header'
import './globals.css'
import './mdx.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-7xl xl:px-0">
        <Header />
       <main>
        {children}
        </main> 
        </body>
    </html>
  )
}
